TOP_LEVEL_PROMPT = '''
You are an expert at conducting market and UX research on social media platforms like Reddit and YouTube. You are tasked with generating a comprehensive report based on a given topic and a list of Reddit posts and comments.

Your goal is to analyze the provided content, extract key insights, and present them in a structured format.

Be sure to really see the big picture. Also, try to identify trends that may not be obvious, but could be useful to a person using the report to make decisions.
'''

GENERAL_TASK_ASSETS = {
    'combine_platform_reports': {
        'task': '''
        Instructions:
        - Combine the reports into an interesting, cohesive, and insightful single report.
        - Ensure that it reads well, like a well written blog post or marketing report (don't explicitly mention this).
        - Aim to highlight the most important insights and trends from the reports, while noting any significant differences between them, given the platforms.
        - Be sure to include quotes and embedded links from the original reports when possible. If you can't embed links directly into the text, Add a "References" section at the end of the report.
        - Ensure that any links are correctly formatted. For example, if a post id is embedded into the text, make sure it is formatted as a link.
         '''.strip(),
        'prompt': 'Combine the following reports into a single report:\n\n{youtube_report}\n\n--------\n\n{reddit_report}',
        'input_variables': ['youtube_report', 'reddit_report'],
        'model': 'gpt-4o',
        'json_schema': {
            'type': 'object',
            'title': 'report',
            'description': 'The combined report generated by the model',
            'properties': {
                'report': {
                    'type': 'string',
                    'description': 'The combined report generated by the model in markdown format, with embedded links and quotes.'
                }
            },
            'required': ['report']
        },
        'temperature': 0,
        'max_tokens': 4096,
    },
    'script_generation': {
        'task': '''
        Create an engaging video script for a newsletter update based on the provided highlights.
        
        Instructions:
        - Start with a brief, engaging introduction
        - For each highlight:
            * Create a smooth transition
            * Present the information in a conversational style
            * Include relevant quotes when available
            * Explain why this matters to the audience
            * Include the post ID or video ID as a link (e.g., [Reddit post](https://www.reddit.com/r/SUBREDDIT/comments/POST_ID) or [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID))
        - End with a call to action and preview of next update
        - Keep the total length suitable for a 2-3 minute video
        - Use natural transitions between topics
        ''',
        'prompt': 'Create a video script from these highlights:\n\nReddit Highlights:\n{reddit_highlights}\n\nYouTube Highlights:\n{youtube_highlights}',
        'input_variables': ['reddit_highlights', 'youtube_highlights'],
        'model': 'gpt-4o',
        'json_schema': {
            'type': 'object',
            'title': 'newsletter_script',
            'description': 'The script generated by the model',
            'properties': {
                'script': {
                    'type': 'string',
                    'description': 'The complete video script in markdown format, including linked post/video IDs'
                },
                'estimated_duration': {
                    'type': 'integer',
                    'description': 'Estimated duration in seconds'
                },
                'sources': {
                    'type': 'array',
                    'items': {
                        'type': 'string'
                    },
                    'description': 'List of post/video IDs used in the script'
                }
            },
            'required': ['script', 'estimated_duration', 'sources']
        }
    }
}

REDDIT_TASK_ASSETS = {

    'multi_post_summary_report': {
        'task': '''
        Generate a comprehensive market and UX research report (dont explicitly mention market or UX research) from multiple Reddit posts and their comments about the topic: {topic}. The report should provide actionable insights for professionals conducting social media analysis.
        
        A rough structure for the report:

        ## Quick Summary
        [Concise overview of key findings and insights. What people are saying?]
        
        [Main body of the report with sections covering the points mentioned in the task, in paragraph and list format]

        ## Conclusion and Recommendations
        [Summary of key takeaways and actionable next steps]

        Provide a quick summary with key findings and insights. Analyze overall sentiment and engagement levels. Identify main themes driving the conversation, user needs, and pain points. Include feature requests, competitive mentions, and emerging trends. Offer demographic insights if discernible. Highlight potential opportunities and areas for improvement. Suggest topics requiring further investigation. Ensure the analysis is adaptable to various search terms, topics, or trends.

        Instructions:
        - Write the report in natural language, suitable for business stakeholders
        - Use clear structure with headings and subheadings for easy navigation
        - With respect to score, relevance, and importance, highlight key insights and their potential business impact.
        - Include relevant quotes or examples, referencing specific posts or comments using their IDs. If possible, embed a link to the post within the text instead of writing out the id.
        - Provide actionable recommendations based on the findings
        - Conclude with a summary of key takeaways and next steps
        - If user concerns are provided, ensure to address them throughout the report
        - Include a list of post IDs that were actually used in the report. If a comment was used, include the parent post ID.
        '''.strip(),
        'prompt': 'Analyze the following Reddit posts and their comments about {topic} to generate a comprehensive market and UX research report:\n\n{posts_and_comments}',
        'input_variables': ['topic', 'posts_and_comments'],
        'model': 'gpt-4o',
        'json_schema': {
            'type': 'object',
            'title': 'Report',
            'description': 'The report generated by the model',
            'properties': {
                'report': {
                    'type': 'string',
                    'description': 'The markdown formatted report generated by the model'
                },
                'posts_used': {
                    'type': 'array',
                    'items': {
                        'type': 'string'
                    },
                    'description': 'List of post IDs used in generating the report'
                }
            },
            'required': ['report', 'posts_used']
        },
        'temperature': 0,
        'max_tokens': 4096,
    },
    'embed_post_urls_in_report': {
        'task': '''
        Enhance the given markdown report by naturally embedding the provided permalinks for the specified Reddit posts and including relevant quotes. Aim to incorporate at least 80% of the provided posts, prioritizing those most relevant to the report's content.

        Instructions:
        - Integrate the provided posts and comments, focusing on those most pertinent to the report.
        - For each selected post or comment, find or create a natural context within the report to embed its link.
        - Integrate links organically into sentences, like "One user [shared their experience](https://www.example.com) with the product," rather than simply replacing IDs or usernames.
        - Create new phrases or sentences if needed to smoothly incorporate links into the narrative.
        - Include relevant quotes from the posts or comments using markdown quote syntax (> for single-line quotes or >>> for multi-line quotes).
        - Focus on integrating the links organically into the text, prioritizing the most relevant posts.
        - Avoid adding long lists of post links for the sake of including them.
        '''.strip(),
        'prompt': 'Embed post links into the following report:\n\nReport:\n{report}\n\nPosts and comments with links:\n{posts_used}',
        'input_variables': ['report', 'posts_used'],
        'model': 'gpt-4o',
        'json_schema': {
            'type': 'object',
            'title': 'Report',
            'description': 'The enhanced markdown report generated by the model',
            'properties': {
                'report': {
                    'type': 'string',
                    'description': 'The enhanced markdown report generated by the model'
                }
            },
            'required': ['report']
        },
        'temperature': 0,
        'max_tokens': 4096,
    },
    'newsletter_highlights': {
        'task': '''
        Analyze the provided Reddit posts and comments to identify the 3 most noteworthy items for an AI/data science newsletter video update.

        Instructions:
        - Select exactly 3 items that would be interesting to AI and data science enthusiasts
        - Each item must be categorized as one of: NEWS, TECHNICAL, or TREND
        - Prioritize items based on:
            * Engagement levels (upvotes, quality of discussion)
            * Novelty and timeliness
            * Practical value to the audience
            * Potential impact on the field
        - For each item, provide:
            * Category
            * Headline (concise, attention-grabbing)
            * Key points (2-3 bullet points)
            * Why it matters (1-2 sentences)
            * Source post ID for reference
        '''.strip(),
        'prompt': 'Analyze these Reddit posts and comments to identify 3 noteworthy items for an AI/data science newsletter:\n\n{posts_and_comments}',
        'input_variables': ['posts_and_comments'],
        'model': 'gpt-4o',
        'json_schema': {
            'type': 'object',
            'title': 'newsletter_highlights',
            'description': 'The highlights generated by the model',
            'properties': {
                'highlights': {
                    'type': 'array',
                    'items': {
                        'type': 'object',
                        'properties': {
                            'category': {
                                'type': 'string',
                                'enum': ['NEWS', 'TECHNICAL', 'TREND']
                            },
                            'headline': {'type': 'string'},
                            'key_points': {
                                'type': 'array',
                                'items': {'type': 'string'},
                                'minItems': 2,
                                'maxItems': 3
                            },
                            'why_it_matters': {'type': 'string'},
                            'post_id': {'type': 'string'}
                        },
                        'required': ['category', 'headline', 'key_points', 'why_it_matters', 'post_id']
                    },
                    'minItems': 3,
                    'maxItems': 3
                }
            },
            'required': ['highlights']
        },
        'temperature': 0,
        'max_tokens': 2048,
    }
}

YOUTUBE_TASK_ASSETS = {

    'multi_video_summary_report': {
        'task': '''
        Generate a comprehensive market and UX research report (do not explicitly mention market or UX research) from multiple YouTube videos and their comments about the topic: {topic}. The report should provide actionable insights for professionals conducting social media analysis.
        
        A rough structure for the report:

        ## Quick Summary
        [Concise overview of key findings and insights. What are people saying?]
        
        [Main body of the report with sections covering the points mentioned in the task, in paragraph and list format]

        ## Conclusion and Recommendations
        [Summary of key takeaways and actionable next steps]

        Provide a quick summary with key findings and insights. Analyze overall sentiment and engagement levels. Identify main themes driving the conversation, user needs, and pain points. Include feature requests, competitive mentions, and emerging trends. Offer demographic insights if discernible. Highlight potential opportunities and areas for improvement. Suggest topics requiring further investigation. Ensure the analysis is adaptable to various search terms, topics, or trends.

        Instructions:
        - Write the report in natural language, suitable for business stakeholders
        - Use clear structure with headings and subheadings for easy navigation
        - With respect to score, relevance, and importance, highlight key insights and their potential business impact.
        - Include relevant quotes or examples, referencing specific videos or comments using their IDs. If possible, embed a link to the video within the text instead of writing out the id.
        - Provide actionable recommendations based on the findings
        - Conclude with a summary of key takeaways and next steps
        - If user concerns are provided, ensure to address them throughout the report
        - Include a list of video IDs that were actually used in the report. If a comment was used, include the parent video ID.
        '''.strip(),
        'prompt': 'Analyze the following YouTube videos and their comments about {topic} to generate a comprehensive market and UX research report:\n\n{videos_and_comments}',
        'input_variables': ['topic', 'videos_and_comments'],
        'model': 'gpt-4o-mini',
        'json_schema': {
            'type': 'object',
            'title': 'Report',
            'description': 'The report generated by the model and the videos used in generating the report',
            'properties': {
                'report': {
                    'type': 'string',
                    'description': 'The markdown formatted report generated by the model'
                },
                'videos_used': {
                    'type': 'array',
                    'items': {
                        'type': 'string'
                    },
                    'description': 'List of video IDs used in generating the report'
                }
            },
            'required': ['report', 'videos_used']
        },
        'temperature': 0,
        'max_tokens': 4096,
    },
    'embed_video_urls_in_report': {
        'task': '''
        Enhance the given markdown report by naturally embedding the provided permalinks for the specified YouTube videos and including relevant quotes. Aim to incorporate at least 80% of the provided videos, prioritizing those most relevant to the report's content.

        Instructions:
        - Integrate the provided videos and comments, focusing on those most pertinent to the report.
        - For each selected video or comment, find or create a natural context within the report to embed its link.
        - Integrate links organically into sentences, like "One viewer [shared their experience](https://www.example.com) with the product," rather than simply replacing IDs or usernames.
        - Create new phrases or sentences if needed to smoothly incorporate links into the narrative.
        - Include relevant quotes from the videos or comments using markdown quote syntax (> for single-line quotes or >>> for multi-line quotes).
        - Focus on integrating the links organically into the text, prioritizing the most relevant videos.
        - Avoid adding long lists of video links for the sake of including them.
        - The URL for each video can be derived by adding youtube.com/watch?v=<video_id>.
        '''.strip(),
        'prompt': 'Embed video links into the following report:\n\nReport:\n{report}\n\nVideos and comments with links:\n{videos_used_string}',
        'input_variables': ['report', 'videos_used_string'],
        'model': 'gpt-4o-mini',
        'json_schema': {
            'type': 'object',
            'title': 'Report',
            'description': 'The enhanced markdown report generated by the model',
            'properties': {
                'report': {
                    'type': 'string',
                    'description': 'The enhanced markdown report generated by the model'
                }
            },
            'required': ['report']
        },
        'temperature': 0,
        'max_tokens': 4096,
    },
    'summarize_transcript': {
        'task': '''
        Instructions:
        - Provide a condensed version of the Youtube transcript.
        - The summary should be written from the perspective of the speaker. And should contain the main points they are trying to convey.
        - The summary should be no more than 7 sentences.
        - Include 1-3 key quotes from the transcript, at most 2 sentences each.
        - Note that the transcript may be missing punctuation, proper formatting, and speaker identification. Do your best to perform the task.
        '''.strip(),
        'prompt': 'Summarize the following YouTube transcript:\n\n{transcript}',
        'input_variables': ['transcript'],
        'model': 'gpt-4o-mini',
        'json_schema': {
            'type': 'object',
            'title': 'transcript_Summary',
            'description': 'The summary of the transcript generated by the model',
            'properties': {
                'transcript_summary': {
                    'type': 'string',
                    'description': 'A condensed version of the transcript, no more than 7 sentences'
                },
                'quotes': {
                    'type': 'array',
                    'items': {
                        'type': 'string'
                    },
                    'description': 'A list of 1-3 key direct quotes from the transcript, each at most 2 sentences long',
                    'minItems': 1,
                    'maxItems': 3
                }
            },
            'required': ['transcript_summary', 'quotes']
        },
        'temperature': 0,
        'max_tokens': 2048,
    },
    'newsletter_highlights': {
        'task': '''
        Analyze the provided YouTube videos and comments to identify the 3 most noteworthy items for an AI/data science newsletter video update.

        Instructions:
        - Select exactly 3 items that would be interesting to AI and data science enthusiasts
        - Each item must be categorized as one of: NEWS, TECHNICAL, or TREND
        - Prioritize items based on:
            * Engagement levels (views, likes, quality of discussion)
            * Novelty and timeliness
            * Practical value to the audience
            * Potential impact on the field
        - For each item, provide:
            * Category
            * Headline (concise, attention-grabbing)
            * Key points (2-3 bullet points)
            * Why it matters (1-2 sentences)
            * Source video ID for reference
        '''.strip(),
        'prompt': 'Analyze these YouTube videos and comments to identify 3 noteworthy items for an AI/data science newsletter:\n\n{videos_and_comments}',
        'input_variables': ['videos_and_comments'],
        'model': 'gpt-4o',
        'json_schema': {
            'type': 'object',
            'title': 'newsletter_highlights',
            'description': 'The highlights generated by the model',
            'properties': {
                'highlights': {
                    'type': 'array',
                    'items': {
                        'type': 'object',
                        'properties': {
                            'category': {
                                'type': 'string',
                                'enum': ['NEWS', 'TECHNICAL', 'TREND']
                            },
                            'headline': {'type': 'string'},
                            'key_points': {
                                'type': 'array',
                                'items': {'type': 'string'},
                                'minItems': 2,
                                'maxItems': 3
                            },
                            'why_it_matters': {'type': 'string'},
                            'video_id': {'type': 'string'}
                        },
                        'required': ['category', 'headline', 'key_points', 'why_it_matters', 'video_id']
                    },
                    'minItems': 3,
                    'maxItems': 3
                }
            },
            'required': ['highlights']
        },
        'temperature': 0,
        'max_tokens': 2048,
    }
}